import { HomeLayouts } from "@/src/Layouts";
import Head from "next/head";
import { AffinityMedia } from "@/src/Utils/Mock/CommonData";
import HomeNavbar from "@/src/Shared/Navbar/HomeNavbar";
import HeroSection from "@/src/Components/homePage/HeroSection";
import Login from "@/src/Components/Login/Login";
import GetTuchModal from "@/src/Components/modal/getTuchModal/getTuchModal";
import MBBSAbroadSection from "@/src/Components/homePage/MBBSAbroadSection";
import BoostSection from "@/src/Components/homePage/BoostSections";
import TestimonialSection from "@/src/Components/homePage/TestimonialSection";
import EventCarousel from "@/src/Components/homePage/EventCarousel";
import StudyAbroadSection from "@/src/Components/homePage/StudyAbroadSection";
import ExploreCollegesSection from "@/src/Components/homePage/ExploreCollegesSection";
import TrendingSection from "@/src/Components/homePage/TrendingSection";
import QaForumSection from "@/src/Components/homePage/QaForumSection";
import AffinityMediaSection from "@/src/Components/homePage/AffinityMediaSection";
import BlogNewsSection from "@/src/Components/homePage/BlogNewsSection";
import AppBannerSection from "@/src/Components/homePage/AppBannerSection";
import GetinTouch from "@/src/Components/homePage/GetinTouch";
import ImageCutout from "@/src/Components/homePage/CardsComp/IMageCutout";
import { AwardCard } from "@/src/Components/homePage/CardsComp/AwardCard";
import useHomePageHook from "@/src/custom-hooks/useHomePageHook";

export default function Home() {
  const {
    CountryListData,
    HeroListData,
    FeturedListData,
    getTuchData,
    handelGetTuchModalOpen,
    handleSlideChange,
    handleLoginButtonClick,
    TestimonialListData,
    EventListData,
    activeExploreCollege,
    StudyAbrod,
    handleExploreTabClick,
    renderContent,
    activeTrendingCollege,
    handleTrendingCollegeTabClick,
    StremOption,
    handleStreamClick,
    CountryTab,
    filterCollegeData,
    AllCollegesData,
    filterCourseData,
    CourseListData,
    active,
    handleTab,
    AffintiyMediaCard,
    customImageData,
    AllStreamData,
    setName,
    setEmailValue,
    setPhone,
    setStreamsSelected,
    emailValue,
    phone,
    StreamsSelected,
    AffintiyBlogCard,
    AffinityNews,
    activeBlogArticalTab,
    handleBlogArticalTabClick,
    isLoginModalOpen,
    setIsLoginModalOpen,
    isGetTuchModalOpen,
    GetTuchHeading,
    selectedTuchType,
    handelGetTuchModalClose,
    name,
    formData
  } = useHomePageHook();

  return (
    <>
      <Head>
        <title>Affinity Education</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeLayouts>
          <section className="h-max mb-16">
            <div>
              <HomeNavbar />
            </div>
            {/* Hero section */}
            <HeroSection HeroListData={HeroListData} />

            <MBBSAbroadSection
              FeturedListData={FeturedListData}
              getTuchData={getTuchData}
              handelGetTuchModalOpen={(tuchType:any) => handelGetTuchModalOpen(tuchType, "Book a call")}
            />

            <BoostSection
              FeturedListData={FeturedListData}
              handleSlideChange={handleSlideChange}
              handleLoginButtonClick={handleLoginButtonClick}
            />

            <TestimonialSection TestimonialListData={TestimonialListData} />

            <EventCarousel EventListData={EventListData} />

            <StudyAbroadSection StudyAbrod={StudyAbrod} />

            <ExploreCollegesSection
              activeExploreCollege={activeExploreCollege}
              handleExploreTabClick={handleExploreTabClick}
              renderContent={renderContent}
            />

            <TrendingSection
              activeTrendingCollege={activeTrendingCollege}
              handleTrendingCollegeTabClick={handleTrendingCollegeTabClick}
              StremOption={StremOption}
              handleStreamClick={handleStreamClick}
              CountryTab={CountryTab}
              filterCollegeData={filterCollegeData}
              AllCollegesData={AllCollegesData}
              filterCourseData={filterCourseData}
              CourseListData={CourseListData}
            />

            <QaForumSection
              handelGetTuchModalOpen={(tuchType:any) => handelGetTuchModalOpen(tuchType, "Ask Your Question")}
            />

            <AffinityMediaSection
              AffinityMedia={AffinityMedia}
              active={active}
              handleTab={handleTab}
              AffintiyMediaCard={AffintiyMediaCard}
              ImageCutout={<ImageCutout customImageData={customImageData} />}
              AwardCard={<AwardCard />}
            />
          </section>

          <GetinTouch
            AllStreamData={AllStreamData}
            getTuchData={getTuchData}
            setName={setName}
            setEmailValue={setEmailValue}
            setPhone={setPhone}
            setStreamsSelected={setStreamsSelected}
            emailValue={emailValue}
            name={name}
            phone={phone}
            StreamsSelected={StreamsSelected}
            handelGetTuchModalOpen={handelGetTuchModalOpen}
          />

          <BlogNewsSection
            AffintiyBlogCard={AffintiyBlogCard}
            AffinityNews={AffinityNews}
            activeBlogArticalTab={activeBlogArticalTab}
            handleBlogArticalTabClick={handleBlogArticalTabClick}
          />

          <AppBannerSection />

          {isLoginModalOpen && (
            <div className="flex">
              <Login
                isLoginModalOpen={isLoginModalOpen}
                setIsLoginModalOpen={setIsLoginModalOpen}
              />
            </div>
          )}
          {isGetTuchModalOpen && (
            <GetTuchModal
              source={"/home"}
              heading={GetTuchHeading}
              tuchType={selectedTuchType}
              isOpen={handelGetTuchModalOpen}
              onClose={handelGetTuchModalClose}
              formData={formData}
            />
          )}
        </HomeLayouts>
      </main>
    </>
  );
}
